export const loginFields = [
  {
    labelText: "Email address",
    labelFor: "email-address",
    id: "emailAddress",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
];

export const signupFields = [
  {
    labelText: "First Name",
    labelFor: "FirstName",
    id: "firstName",
    name: "firstName",
    type: "text",
    autoComplete: "firstName",
    isRequired: true,
    placeholder: "First Name",
  },
  {
    labelText: "Last Name",
    labelFor: "LastName",
    id: "lastName",
    name: "lastName",
    type: "text",
    autoComplete: "lastName",
    isRequired: true,
    placeholder: "Last Name",
  },
  {
    labelText: "Email address",
    labelFor: "email-address",
    id: "emailAddress",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "Phone Number",
    labelFor: "phoneNumber",
    id: "phoneNumber",
    name: "phoneNumber",
    type: "number",
    autoComplete: "phoneNumber",
    isRequired: true,
    placeholder: "Phone Number",
  },
  {
    labelText: "Age",
    labelFor: "age",
    id: "age",
    name: "age",
    type: "number",
    autoComplete: "age",
    isRequired: true,
    placeholder: "Age",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
];
